### ISSUE TITLE
Not all functions are part of namespace

### ISSUE THREAD

**Issue by jae0** [Beothuk/bio.utilities#1]
I am not sure why but there are many functions that are not found in the exported namespace.

**Comment by MMMcMahon** [comment]
All of the functions had '@export added at their start, and while this does modify the namespace, it is apparently insufficient to generate the necessary md files in the MAN folder.  I added titles and descriptions to all of the missing functions, and they all now show up.  Feel free to improve the documentation wherever you can, and claim the functions your wrote by adding your name as an author.
